### ISSUE TITLE
Extract key based on hash fragment

### ISSUE THREAD

**Issue by mattcollier** [AnthonyRonning/vc-testing#1]
I see that you have a branch where you've got the entire DID document in place which is great.

The next step would be to implement code along these lines that detects a hash fragment and extracts the key material from the DID document instead of having a separate document in the document loader.

So, if you see `did:btcr:foo` without a hash fragment, do what you're doing now (return the full DID), if you see `did:btcr:foo#bar`, get the full DID document, then locate the key document in the DID and return *just* that part of the document.

https://github.com/veres-one/did-veres-one/blob/master/lib/VeresOneClient.js#L42-L49
which is called from:
https://github.com/veres-one/did-veres-one/blob/master/lib/VeresOne.js#L143

**Comment by AnthonyRonning** [comment]
Thanks for those code samples! Made it really easy to integrate this. 

Part of the reason I branched off too is to "implement" a VC capable BTCR doc. Until [btcr-did-tools-js](https://github.com/WebOfTrustInfo/btcr-did-tools-js) is updated, we may be limited on any "true" resolving. The resolver currently resolves `did:btcr:xg35-jzrx-qtyt-jqr` as the below, which probably won't allow for verification unless we want to construct `publicKey`, `authentication`, and `assertionMethod` ourselves in the document loader until then. 

```
{
    "@context": "https://w3id.org/btcr/v1",
    "id": "did:btcr:xg35-jzrx-qtyt-jqr",
    "publicKey": [
        {
            "id": "did:btcr:xg35-jzrx-qtyt-jqr#keys-1",
            "owner": "did:btcr:xg35-jzrx-qtyt-jqr",
            "type": "EcdsaSecp256k1VerificationKey2019",
            "publicKeyHex": "03ceba0298eb4a026b9d9b1486c90c088a92e15892dd4c4044e3e6ad076c9b262f"
        }
    ],
    "authentication": [
        {
            "type": "EcdsaSecp256k1VerificationKey2019",
            "publicKey": "#keys-1"
        }
    ],
    "SatoshiAuditTrail": [
        {
            "chain": "testnet",
            "blockhash": "0000000000000011fd70846401c79e3b04ba2f0b75c6d160cbaae71287a9c1b7",
            "blockindex": 195,
            "outputindex": 0,
            "blocktime": "2018-07-16T22:45:25Z",
            "time": 1499501000,
            "timereceived": "2018-07-16T22:45:25Z",
            "burn-fee": -0.05
        }
    ]
}
```

**Comment by AnthonyRonning** [comment]
Got a branch here implementing a vc capable btcr resolver: https://github.com/WebOfTrustInfo/btcr-did-tools-js/pull/9

Implemented it here and got it resolving / verifying with real did's. 

Main problem is btcr context url doesn't work so had to hack in `context['@context'] = 'https://w3id.org/did/v0.11';`. 

Gonna merge this in
